In [1]:
import numpy as np
import kernel
y1, y2 = np.random.binomial(1, 0.5, (250,)), np.random.binomial(1, 0.75, (100,))
x1, x2 = np.random.normal(loc = y1 * 1.5, scale= 1, size=(250,)), np.random.normal(loc = y2 * 1, scale= 1.5, size=(100,))
x1, x2 = np.reshape(x1, (250, 1)), x2.reshape((100, 1))

In [2]:
# Unlabeled classifier; lipton
import unsupervised
n, d = np.shape(x1)
beta, kernel_df = 5, 5
cl4 = unsupervised.WithoutLabelClassifier(kernel_df=kernel_df, beta=beta)
cl4.fit(x1, y1, x2, method='lipton')
y2 == cl4.predict(x2)

[0.271 0.729]


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [7]:
cl4 = classifier.KDEClassifier(kernel_df=kernel_df, bandwidth=bandwidth)
prop_target = 0.75
cl4.fit(x1, y1, [1-prop_target, prop_target])
cl3.predict(x2) == y2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [15]:
a = 4 * (2 ** np.linspace(0, 9, 10))
b = np.repeat(50, 10)
c = 4 * (2 ** np.linspace(0, 7, 8))
d = np.repeat(50, 8)
e1 = np.column_stack((a, b))
e2 = np.column_stack((d, c))
sample_sizes1 = np.vstack((e1, e2))
label1 = np.repeat(False, 10)

a = 25 * (2 ** np.linspace(3, 9, 7))
b = np.repeat(50, 7)
e1 = np.column_stack((a-b, b))
e2 = np.column_stack((b, a-b))
sample_sizes2 = np.vstack((e1, e2))
label2 = np.repeat(True, 7)

sample_sizes = np.vstack((sample_sizes1, sample_sizes2))
sample_sizes = np.array(sample_sizes, dtype = 'int32')
label = np.array([False] * 18 + [True] * 14, dtype='bool')

In [16]:
np.save('sample_sizes.npy', sample_sizes)
np.save('label.npy', label)

In [17]:
sample_sizes

array([[    4,    50],
       [    8,    50],
       [   16,    50],
       [   32,    50],
       [   64,    50],
       [  128,    50],
       [  256,    50],
       [  512,    50],
       [ 1024,    50],
       [ 2048,    50],
       [   50,     4],
       [   50,     8],
       [   50,    16],
       [   50,    32],
       [   50,    64],
       [   50,   128],
       [   50,   256],
       [   50,   512],
       [  150,    50],
       [  350,    50],
       [  750,    50],
       [ 1550,    50],
       [ 3150,    50],
       [ 6350,    50],
       [12750,    50],
       [   50,   150],
       [   50,   350],
       [   50,   750],
       [   50,  1550],
       [   50,  3150],
       [   50,  6350],
       [   50, 12750]], dtype=int32)

In [14]:
label

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [2]:
import prop_estimation
prop_estimation.lipton_method(x1, y1, x2)

(0.74, array([0.5       , 1.54166667]))

In [2]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
import data


In [7]:
D = data.DataGenerator(d = 4)
x_source, y_source = D.getData(100, 0.5, 2)
x_target, y_target = D.getData(100, 0.75, 2)
m, d = np.shape(x_source)
prop_source = np.mean(y_source)

cl = LogisticRegression(penalty='none')
cl.fit(x_source, y_source)
confusion_matrix = metrics.confusion_matrix(cl.predict(x_source),y_source)/m 
print(confusion_matrix)
if np.prod(np.diag(confusion_matrix)) == 0:
    confusion_matrix = confusion_matrix + 0.01 * np.identity(d)
print(confusion_matrix)
confusion_matrix = confusion_matrix/np.sum(confusion_matrix)
prop_target = np.mean(cl.predict(x_target))
    
xi = np.array([1-prop_target,prop_target])
w = np.matmul(np.linalg.inv(confusion_matrix),xi)
prop_targets = w*np.array([1-prop_source, prop_source])
prop_targets

[[0.41 0.08]
 [0.05 0.46]]
[[0.41 0.08]
 [0.05 0.46]]


array([0.17742145, 0.82257855])

In [5]:
np.matmul(np.linalg.inv(confusion_matrix), xi)

array([1.53061224, 0.51020408])

In [9]:
w

array([1.10036881, 0.90279241])

In [7]:
w * 

11

In [8]:
prop_target

0.41

In [9]:
prop_targets

array([0.53531976, 0.4644503 ])

In [10]:
w

array([0.95592814, 1.05556886])

In [11]:
np.sum(confusion_matrix)

1.0

In [17]:
np.prod(np.diag(confusion_matrix))

0.08639999999999999

In [6]:
np.sum(y2)

70

In [9]:
4 * 2 ** np.array(range(10))

array([   4,    8,   16,   32,   64,  128,  256,  512, 1024, 2048])

In [18]:
x = np.array([1, 2, 3, 4])
x>3

array([False, False, False,  True])

In [20]:
np.any(x>5)

False