In [1]:
import numpy as np
import kernel
y1, y2 = np.random.binomial(1, 0.5, (100,)), np.random.binomial(1, 0.75, (100,))
x1, x2 = np.random.normal(loc = y1 * 1, scale= 0.1, size=(100,)), np.random.normal(loc = y2 * 1, scale= 0.1, size=(100,))
x1, x2 = np.reshape(x1, (100, 1)), x2.reshape((100, 1))

In [2]:
import classifier
cl1 = classifier.KDEClassifierOptimalParameter()
cl1.fit(x1, y1)
cl1.predict(x2) == y2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [3]:
import supervised
cl2 = supervised.WithLabelClassifier(bandwidth=0.3, kernel_df=4)
cl2.fit(x1, y1, x2, y2)
cl2.predict(x2) == y2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [4]:
import mixture_classifier
cl3 = mixture_classifier.MixtureClassifier()
cl3.fit(cl1._classifier, x2, y2)
cl3.predict(x2) == y2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [5]:
cl4 = mixture_classifier.OptimalMixtureClassifier()
cl4.fit2(x1, y1, x2, y2)
cl4.predict(x2) == y2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [4]:
# Unlabeled classifier; lipton
import unsupervised
n, d = np.shape(x1)
beta, kernel_df = 5, 5
bandwidth = n ** (-1/(2*beta+d))
cl4 = unsupervised.WithoutLabelClassifier(kernel_df=kernel_df, bandwidth=bandwidth)
cl4.fit(x1, y1, x2, method='lipton')
y2 == cl4.predict(x2)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [7]:
cl4 = classifier.KDEClassifier(kernel_df=kernel_df, bandwidth=bandwidth)
prop_target = 0.75
cl4.fit(x1, y1, [1-prop_target, prop_target])
cl3.predict(x2) == y2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [8]:
a = 25 * (2 ** np.linspace(0, 9, 10))
b = np.repeat(100, 10)
e1 = np.column_stack((a, b))
e2 = np.column_stack((b, a))
sample_sizes1 = np.vstack((e1, e2))
label1 = np.repeat(False, 10)

a = 25 * (2 ** np.linspace(3, 9, 7))
b = np.repeat(100, 7)
e1 = np.column_stack((a-b, b))
e2 = np.column_stack((b, a-b))
sample_sizes2 = np.vstack((e1, e2))
label2 = np.repeat(True, 7)

sample_sizes = np.vstack((sample_sizes1, sample_sizes2))
sample_sizes = np.array(sample_sizes, dtype = 'int32')
label = np.array([False] * 20 + [True] * 14, dtype='bool')

In [9]:
np.save('sample_sizes.npy', sample_sizes)
np.save('label.npy', label)

In [10]:
sample_sizes

array([[   25,   100],
       [   50,   100],
       [  100,   100],
       [  200,   100],
       [  400,   100],
       [  800,   100],
       [ 1600,   100],
       [ 3200,   100],
       [ 6400,   100],
       [12800,   100],
       [  100,    25],
       [  100,    50],
       [  100,   100],
       [  100,   200],
       [  100,   400],
       [  100,   800],
       [  100,  1600],
       [  100,  3200],
       [  100,  6400],
       [  100, 12800],
       [  100,   100],
       [  300,   100],
       [  700,   100],
       [ 1500,   100],
       [ 3100,   100],
       [ 6300,   100],
       [12700,   100],
       [  100,   100],
       [  100,   300],
       [  100,   700],
       [  100,  1500],
       [  100,  3100],
       [  100,  6300],
       [  100, 12700]], dtype=int32)

In [7]:
label

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [20]:
i = (25 + 15 * 100 + 17 * 100 )
iteration = i % 100

j = i // 100
k = j % 17

j = j // 17
beta = j
i

3225

In [19]:
iteration, k, beta

(25, 15, 1)

In [3]:
import setup
parameter = 3, 3, 0.75
setup.excess_risk(parameter, x1, y1, x2, y2, x2, y2, 0.02, True)

{'kernel_df': 3,
 'beta': 3,
 'bayes_error': 0.02,
 'n_source': 100,
 'n_target': 100,
 'classical': 0.0,
 'labeled': 0.0,
 'mixture': 0.0}

In [1]:
import experiment
experiment.f('a', 800, 800, 0.75)

{'kernel_df': 3, 'beta': 3, 'bayes_error': 0.0191, 'n_source': 800, 'n_target': 800, 'classical': 0.14, 'labeled': 0.08, 'iter': 0}


In [2]:
experiment.f('a', 800, 800, 0.75, labeled = False)

{'kernel_df': 3, 'beta': 3, 'bayes_error': 0.0186, 'n_source': 800, 'n_target': 800, 'lipton': 0.23, 'oracle': 0.06, 'iter': 0}


In [3]:
!python3 experiment.py 162

Done
n_s: 800.0, n_t: 800.0, kernel_df: 5, beta: 5, iter: 2, label: True
{'kernel_df': 5, 'beta': 5, 'bayes_error': 0.018, 'n_source': 800, 'n_target': 800, 'classical': 0.11, 'labeled': 0.08, 'iter': 2}
